export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_PRODUCTS = "fetch_products";
export const FETCH_PRODUCT = "fetch_product";

export const CREATE_COMMENT = {
	ERROR: 'CREATE_COMMENT_ERROR'
}

export const GET_COMMENTS = {
  FINISHED: 'GET_COMMENTS_FINISHED',
  ERROR: 'GET_COMMENTS_ERROR'
}

export const GET_USER = {
    FINISHED: 'GET_USER_FINISHED',
    ERROR: 'GET_USER_ERROR'
}

export const LOGIN_USER = {
    ERROR: 'LOGIN_USER_ERROR'
}

export const REGISTER_USER = {
    ERROR: 'REGISTER_USER_ERROR'
}

export const SEARCH_PRODUCTS = {
    FINISHED: 'SEARCH_PRODUCTS_FINISHED',
    ERROR: 'SEARCH_PRODUCTS_ERROR'
}

export const REQUEST_BORROW_PRODUCT = {
    FINISHED: 'REQUEST_BORROW_PRODUCT_FINISHED',
    ERROR: 'REQUEST_BORROW_PRODUCT_ERROR'
}

export const FETCH_TRANSACTIONS = {
    FETCHING: 'FETCH_TRANSACTIONS_FETCHING',
    FINISHED: 'FETCH_TRANSACTIONS_FINISHED',
    ERROR: 'FETCH_TRANSACTIONS_ERROR'
}

export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS'
