export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// export const SEARCH = "SEARCH";
// export const GET_USER_PROFILE = "GET_USER_PROFILE";

// Products
export const FETCH_PRODUCTS = "fetch_products";
export const FETCH_PRODUCT = "fetch_product";

export const GET_USER = {
    FINISHED: 'GET_USER_FINISHED',
    ERROR: 'GET_USER_ERROR'
}

export const LOGIN_USER = {
    ERROR: 'LOGIN_USER_ERROR'
}

export const REGISTER_USER = {
    ERROR: 'REGISTER_USER_ERROR'
}

export const SEARCH_PRODUCTS = {
    FETCH: 'SEARCH_PRODUCTS_FETCH',
    FINISHED: 'SEARCH_PRODUCTS_FINISHED',
    ERROR: 'SEARCH_PRODUCTS_ERROR'
}

export const REQUEST_BORROW_PRODUCT = {
    FINISHED: 'REQUEST_BORROW_PRODUCT_FINISHED',
    ERROR: 'REQUEST_BORROW_PRODUCT_ERROR'
}
